--- 
title: "An Introduction to Neuroscience"
author: "Edited by Elizabeth Kirby, PhD"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rcalinjageman/an_introduction_to_neuroscience
description: "This is a free, open-source Introduction to Textbook for undergraduate coursework.  Chapter 2 is in draft form; more chapters to come."
---

# Introduction

This is an early draft of a chapter from a new Introduction to Neuroscience textbook, an effort that is:

- Open source, available free to students

- Faculty created

- Peer reviewed (in progress)

- High quality, including professional illustrations and learning resources

***

This textbook is edited by [Elizabeth Kirby](https://u.osu.edu/kirbylab/), PhD and supported by funding from the [National Science Foundation](https://www.nsf.gov/awardsearch/simpleSearchResult?queryText=elizabeth+kirby&ActiveAwards=true)


This early preview of the book is posted by [Bob Calin-Jageman](https://calin-jageman.net/lab/), an author Chapter (\@ref(neurophysiology) on neurophysiology.  The purpose of posting this early-stage chapter here is:

- To make it available for Dr. Bob's Introduction to Neuroscience students

- To gather feedback from others interested in this chapter or project


If you have any feedback, find a typo, notice an innaccuracy, etc... please submit your comments as in Issue on github here: https://github.com/rcalinjageman/an_introduction_to_neuroscience/issues

***

You can access early-stage draft in three different formats:

- [Online, in HTML](https://rcalinjageman.github.io/an_introduction_to_neuroscience/)

- [Pdf](https://rcalinjageman.github.io/an_introduction_to_neuroscience/docs/Intro_to_Neuroscience.pdf)

- [epub](https://rcalinjageman.github.io/an_introduction_to_neuroscience/docs/Intro_to_Neuroscience.epub)
